export const LOGIN_PENDING = 'LOGIN_PENDING';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const GOOGLE_LOGIN_PENDING = 'GOOGLE_LOGIN_PENDING';
export const GOOGLE_LOGIN_SUCCESS = 'GOOGLE_LOGIN_SUCCESS';
export const GOOGLE_LOGIN_FAIL = 'GOOGLE_LOGIN_FAIL';

export const FACEBOOK_LOGIN_PENDING = 'FACEBOOK_LOGIN_PENDING';
export const FACEBOOK_LOGIN_SUCCESS = 'FACEBOOK_LOGIN_SUCCESS';
export const FACEBOOK_LOGIN_FAIL = 'FACEBOOK_LOGIN_FAIL';

export const NUMBER_SIGNUP_PENDING = 'NUMBER_SIGNUP_PENDING';
export const NUMBER_SIGNUP_SUCCESS = 'NUMBER_SIGNUP_SUCCESS';
export const NUMBER_SIGNUP_FAIL = 'NUMBER_SIGNUP_FAIL';

export const SHOW_LIBRARY_PENDING = 'SHOW_LIBRARY_PENDING';
export const SHOW_LIBRARY_SUCCESS = 'SHOW_LIBRARY_SUCCESS';
export const SHOW_LIBRARY_FAIL = 'SHOW_LIBRARY_FAIL';

export const SHOW_LIBRARY_DETAILS_PENDING = 'SHOW_LIBRARY_DETAILS_PENDING';
export const SHOW_LIBRARY_DETAILS_SUCCESS = 'SHOW_LIBRARY_DETAILS_SUCCESS';
export const SHOW_LIBRARY_DETAILS_FAIL = 'SHOW_LIBRARY_DETAILS_FAIL';

export const SHOW_ALL_LIBRARY_PENDING = 'SHOW_ALL_LIBRARY_PENDING';
export const SHOW_ALL_LIBRARY_SUCCESS = 'SHOW_ALL_LIBRARY_SUCCESS';
export const SHOW_ALL_LIBRARY_FAIL = 'SHOW_ALL_LIBRARY_FAIL';

export const VERIFY_PAYMENT_PENDING = 'VERIFY_PAYMENT_PENDING';
export const VERIFY_PAYMENT_SUCCESS = 'VERIFY_PAYMENT_SUCCESS';
export const VERIFY_PAYMENT_FAIL = 'VERIFY_PAYMENT_FAIL';

export const SHOW_ORDER_PENDING = 'SHOW_ORDER_PENDING';
export const SHOW_ORDER_SUCCESS = 'SHOW_ORDER_SUCCESS';
export const SHOW_ORDER_FAIL = 'SHOW_ORDER_FAIL';

export const RAZORPAY_ORDER_PENDING = 'RAZORPAY_ORDER_PENDING';
export const RAZORPAY_ORDER_SUCCESS = 'RAZORPAY_ORDER_SUCCESS';
export const RAZORPAY_ORDER_FAIL = 'RAZORPAY_ORDER_FAIL';

export const ADD_TO_CART_PENDING = 'ADD_TO_CART_PENDING';
export const ADD_TO_CART_SUCCESS = 'ADD_TO_CART_SUCCESS';
export const ADD_TO_CART_FAIL = 'ADD_TO_CART_FAIL';

export const REMOVE_ITEM_PENDING = 'REMOVE_ITEM_PENDING';
export const REMOVE_ITEM_SUCCESS = 'REMOVE_ITEM_SUCCESS';
export const REMOVE_ITEM_FAIL = 'REMOVE_ITEM_FAIL';

export const GET_CART_PENDING = 'GET_CART_PENDING';
export const GET_CART_SUCCESS = 'GET_CART_SUCCESS';
export const GET_CART_FAIL = 'GET_CART_FAIL';

export const RAZORPAY_VERIFICATION_DONATION_PENDING = 'RAZORPAY_VERIFICATION_DONATION_PENDING';
export const RAZORPAY_VERIFICATION_DONATION_SUCCESS = 'RAZORPAY_VERIFICATION_DONATION_SUCCESS';
export const RAZORPAY_VERIFICATION_DONATION_FAIL = 'RAZORPAY_VERIFICATION_DONATION_FAIL';

export const DONATION_PAYMENT_PENDING = 'DONATION_PAYMENT_PENDING';
export const DONATION_PAYMENT_SUCCESS = 'DONATION_PAYMENT_SUCCESS';
export const DONATION_PAYMENT_FAIL = 'DONATION_PAYMENT_FAIL';

export const GET_DONATION_PENDING = 'GET_DONATION_PENDING';
export const GET_DONATION_SUCCESS = 'GET_DONATION_SUCCESS';
export const GET_DONATION_FAIL = 'GET_DONATION_FAIL';

export const CONFIRM_DONATION_PENDING = 'CONFIRM_DONATION_PENDING';
export const CONFIRM_DONATION_SUCCESS = 'CONFIRM_DONATION_SUCCESS';
export const CONFIRM_DONATION_FAIL = 'CONFIRM_DONATION_FAIL';

export const SIGN_UP_PENDING = 'SIGN_UP_PENDING';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_FAIL = 'SIGN_UP_FAIL';

export const SHOW_ALL_PRODUCTS_PENDING = 'SHOW_ALL_PRODUCTS_PENDING';
export const SHOW_ALL_PRODUCTS_SUCCESS = 'SHOW_ALL_PRODUCTS_SUCCESS';
export const SHOW_ALL_PRODUCTS_FAIL = 'SHOW_ALL_PRODUCTS_FAIL';

export const SHOW_USER_PENDING = 'SHOW_USER_PENDING';
export const SHOW_USER_SUCCESS = 'SHOW_USER_SUCCESS';
export const SHOW_USER_FAIL = 'SHOW_USER_FAIL';

export const ADD_COMMENT_AND_RATING_PENDING = 'ADD_COMMENT_AND_RATING_PENDING';
export const ADD_COMMENT_AND_RATING_SUCCESS = 'ADD_COMMENT_AND_RATING_SUCCESS';
export const ADD_COMMENT_AND_RATING_FAIL = 'ADD_COMMENT_AND_RATING_FAIL';

export const GET_ONE_PRODUCT_PENDING = 'GET_ONE_PRODUCT_PENDING';
export const GET_ONE_PRODUCT_SUCCESS = 'GET_ONE_PRODUCT_SUCCESS';
export const GET_ONE_PRODUCT_FAIL = 'GET_ONE_PRODUCT_FAIL';

export const GET_ONE_ORDER_PENDING = 'GET_ONE_ORDER_PENDING';
export const GET_ONE_ORDER_SUCCESS = 'GET_ONE_ORDER_SUCCESS';
export const GET_ONE_ORDER_FAIL = 'GET_ONE_ORDER_FAIL';

export const HOME_PENDING = 'HOME_PENDING';
export const HOME_SUCCESS = 'HOME_SUCCESS';
export const HOME_FAIL = 'HOME_FAIL';

export const SHIPPING_PENDING = 'SHIPPING_PENDING';
export const SHIPPING_SUCCESS = 'SHIPPING_SUCCESS';
export const SHIPPING_FAIL = 'SHIPPING_FAIL';

export const CART_ITEMS_PENDING = 'CART_ITEMS_PENDING';
export const CART_ITEMS_SUCCESS = 'CART_ITEMS_SUCCESS';
export const CART_ITEMS_FAIL = 'CART_ITEMS_FAIL';

export const GET_LIBRARY_PENDING = 'GET_LIBRARY_PENDING';
export const GET_LIBRARY_SUCCESS = 'GET_LIBRARY_SUCCESS';
export const GET_LIBRARY_FAIL = 'GET_LIBRARY_FAIL';

export const OTP_PENDING = 'OTP_PENDING';
export const OTP_SUCCESS = 'OTP_SUCCESS';
export const OTP_FAIL = 'OTP_FAIL';

export const VERIFY_OTP_PENDING = 'VERIFY_OTP_PENDING';
export const VERIFY_OTP_SUCCESS = 'VERIFY_OTP_SUCCESS';
export const VERIFY_OTP_FAIL = 'VERIFY_OTP_FAIL';

export const GET_LIBRARY_URL_PENDING = 'GET_LIBRARY_URL_PENDING';
export const GET_LIBRARY_URL_SUCCESS = 'GET_LIBRARY_URL_SUCCESS';
export const GET_LIBRARY_URL_FAIL = 'GET_LIBRARY_URL_FAIL';

export const GET_SEARCH_LIBRARY_PENDING = 'GET_SEARCH_LIBRARY_PENDING';
export const GET_SEARCH_LIBRARY_SUCCESS = 'GET_SEARCH_LIBRARY_SUCCESS';
export const GET_SEARCH_LIBRARY_FAIL = 'GET_SEARCH_LIBRARY_FAIL';

export const GET_TOGETHER_PENDING = 'GET_TOGETHER_PENDING';
export const GET_TOGETHER_SUCCESS = 'GET_TOGETHER_SUCCESS';
export const GET_TOGETHER_FAIL = 'GET_TOGETHER_FAIL';

export const SHOW_LIB_BY_CAT_PENDING = 'SHOW_LIB_BY_CAT_PENDING';
export const SHOW_LIB_BY_CAT_SUCCESS = 'SHOW_LIB_BY_CAT_SUCCESS';
export const SHOW_LIB_BY_CAT_FAIL = 'SHOW_LIB_BY_CAT_FAIL';

export const GET_SOCIAL_PENDING = 'GET_SOCIAL_PENDING';
export const GET_SOCIAL_SUCCESS = 'GET_SOCIAL_SUCCESS';
export const GET_SOCIAL_FAIL = 'GET_SOCIAL_FAIL';

export const GET_COURSE_PENDING = 'GET_COURSE_PENDING';
export const GET_COURSE_SUCCESS = 'GET_COURSE_SUCCESS';
export const GET_COURSE_FAIL = 'GET_COURSE_FAIL';

export const GET_SINGLE_COURSE_PENDING = 'GET_SINGLE_COURSE_PENDING';
export const GET_SINGLE_COURSE_SUCCESS = 'GET_SINGLE_COURSE_SUCCESS';
export const GET_SINGLE_COURSE_FAIL = 'GET_SINGLE_COURSE_FAIL';

export const GET_TAGS_PENDING = 'GET_TAGS_PENDING';
export const GET_TAGS_SUCCESS = 'GET_TAGS_SUCCESS';
export const GET_TAGS_FAIL = 'GET_TAGS_FAIL';

export const RAZORPAY_DONATION_PENDING = 'RAZORPAY_DONATION_PENDING';
export const RAZORPAY_DONATION_SUCCESS = 'RAZORPAY_DONATION_SUCCESS';
export const RAZORPAY_DONATION_FAIL = 'RAZORPAY_DONATION_FAIL';

export const RAZORPAY_DONATION_VERIFICATION_PENDING = 'RAZORPAY_DONATION_VERIFICATION_PENDING';
export const RAZORPAY_DONATION_VERIFICATION_SUCCESS = 'RAZORPAY_DONATION_VERIFICATION_SUCCESS';
export const RAZORPAY_DONATION_VERIFICATION_FAIL = 'RAZORPAY_DONATION_VERIFICATION_FAIL';
